### ISSUE TITLE
La navbar est trop grande sur mobile

### ISSUE THREAD

**Issue by seiteta** [SocieteNumerique/societenumerique.github.io#3]
### Comportement attendu
La navbar ne fait pas plus d'une ligne.

### Comportement réel
La navbar fait deux lignes.
<img width="361" alt="capture d ecran 2018-05-31 a 11 14 00" src="https://user-images.githubusercontent.com/5756228/40773632-bd30aa82-64c3-11e8-890d-c0942fd0db1f.png">

### Reproduction du comportement
Utiliser un mobile de résolution 360x640 (par exemple le Nexus 5) sur la page d'accueil (https://inclusion.societenumerique.gouv.fr/).

### Proposition de résolution
Réduire la taille du logo et/ou supprimer le logo et/ou utiliser un menu sandwich.

**Comment by MarjolaineLB** [comment]
mettre un menu burger pour 3 liens nous paraît un peu dommage.
J'ai supprimé le logo du coup, à voir si c'est ok !

**Comment by seiteta** [comment]
OK pour nous 👌
